### ISSUE TITLE
Recreating this doesn't generate the full Tailwind stylesheet

### ISSUE THREAD

**Issue by krazov** [react-microfrontends/styleguide#10]
I am working on a Single SPA app and I am trying to recreate the solution from this repo, but it only generates the base selectors from TailwindCSS, but nothing else. Is there some secret step that is not obvious from the code?

**Comment by krazov** [comment]
I found the reason: the example here is using Tailwind V2, which behaves differently than V3. Hence, the example is not useful in my case. But the issue is no longer needed.

**Comment by ruiaraujolink** [comment]
@krazov did you find a way to put tailwind v3 working? thanks

**Comment by krazov** [comment]
@ruiaraujolink, kind of. Our styleguide library has now all the visual components that are imported elsewhere. Then, Tailwind is generating all the classes that are used.

I considered feeding Tailwind with all our apps, but a change in any of them would require redeploying the styleguide as well, and that would be too much of a tight coupling.

**Comment by ruiaraujolink** [comment]
Make sense.

I will try to put tailwind 3 working with simple-spa since I'm starting a new project.

Thanks anyway

**Comment by ruiaraujolink** [comment]
I think this is not possible since the tailwind v3 has a jit engine that removes all classes that are not used, and since some classes are used in other mfe, the generated css does not include these classes.

**Comment by krazov** [comment]
What's more, styleguide as presented in this repo has basically no classes of its own.

**Comment by ruiaraujo012** [comment]
Exactly. I've switch back to v2.

**Comment by xtfei** [comment]
> Make sense.
> 
> I will try to put tailwind 3 working with simple-spa since I'm starting a new project.
> 
> Thanks anyway


I found a way to solve this problem by first putting all the associated projects into the same mono repository and then configuring tailwind.config.js inside styleguide to scan all these projects.

**Comment by msalahz** [comment]
> > Make sense.
> > I will try to put tailwind 3 working with simple-spa since I'm starting a new project.
> > Thanks anyway
> 
> I found a way to solve this problem by first putting all the associated projects into the same mono repository and then configuring tailwind.config.js inside styleguide to scan all these projects.

@xtfei: 
Does it use TailwindCSS v3?
Can you share a working project?
