### ISSUE TITLE
This implementation no longer works with Tailwind v3

### ISSUE THREAD

**Issue by thejayhaykid** [react-microfrontends/styleguide#11]
Following this implementation for the webpack config when added to a new application created with the Single SPA CLI.

After creating the project using `npx --yes create-single-spa --use-yarn --module-type app-parcel --framework react --typescript` and answering the prompts, I then 

- `yarn add -D tailwindcss postcss postcss-loader autoprefixer`
- Create an `index.css` file with [Tailwind's recommended contents](https://tailwindcss.com/docs/installation/using-postcss), import that into my `root.component.tsx` file
- Create the necessary `postcss.config.js` and `tailwind.config.js` files and put contents from the above link into those respective files

I then update the `webpack.config.js` file to match what is in this repository:
```js
//... not necessary for this issue, it's the default stuff up here
const config = mergeWithRules({
    module: {
      rules: {
        test: 'match',
        use: 'replace',
      },
    },
  })(defaultConfig, {
    // customize the webpack config here
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: ['style-loader', 'css-loader', 'postcss-loader'],
        },
      ],
    },
  });

  return config;
//...
```

I then add `className="text-3xl font-bold underline"` to the JSX element being returned in `root.component.tsx` and run the project and my root-config project. The text content appears, unstyled, unaffected by the tailwind styles that should be applied.

@joeldenning any help here would be appreciated

**Comment by mdtalha109** [comment]
Have you got any solution for this?

**Comment by thejayhaykid** [comment]
Yes. 

I do have tailwind working with single-spa using postCSS. Here is the `webpack.config.js`, notice we use mergeWithRules instead of just merge as that caused issues that we couldn't figure out

```js
const config = mergeWithRules({
    module: {
      rules: {
        test: 'match',
        use: 'replace',
      },
    },
  })(defaultConfig, {
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: [
            require.resolve('style-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            require.resolve('css-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            'postcss-loader',
          ],
        },
      ],
    },
});
```

And then we setup tailwind using the https://tailwindcss.com/docs/installation/using-postcss

**Comment by mdtalha-eronkan** [comment]
facing this issue:

./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./src/global.css 39 bytes [built] [code generated] [1 error]

ERROR in ./src/global.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./src/global.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) /home/eronkan/Desktop/Project/sguide/src/global.css Unknown word

  1 | 
> 2 |       import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
 @ ./src/global.css 8:6-251 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-221 77:0-221 78:22-29 78:33-47 78:50-64 55:4-68:5
 @ ./src/eronkan-sguide.js 1:0-22

webpack 5.88.2 compiled with 1 error in 1851 ms


global.css file:

@tailwind base;
@tailwind components;
@tailwind utilities;


webpack config:


const {merge} = require('webpack-merge')
const singleSpaDefaults = require('webpack-config-single-spa-react')


module.exports = (webpackConfigEnv, argv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "eronkan",
    projectName: "sguide",
    webpackConfigEnv,
    argv,
  });

  return merge(defaultConfig, {
    // modify the webpack config however you'd like to by adding to this object
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: [
            require.resolve('style-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            require.resolve('css-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            'postcss-loader',
          ],
        },
      ],
    },
  });
};

**Comment by mdtalha-eronkan** [comment]
`facing this issue:

./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./src/global.css 39 bytes [built] [code generated] [1 error]

ERROR in ./src/global.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./src/global.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) /home/eronkan/Desktop/Project/sguide/src/global.css Unknown word

  1 | 
> 2 |       import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
 @ ./src/global.css 8:6-251 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-221 77:0-221 78:22-29 78:33-47 78:50-64 55:4-68:5
 @ ./src/eronkan-sguide.js 1:0-22

webpack 5.88.2 compiled with 1 error in 1851 ms


global.css file:

@tailwind base;
@tailwind components;
@tailwind utilities;


webpack config:


const {merge} = require('webpack-merge')
const singleSpaDefaults = require('webpack-config-single-spa-react')


module.exports = (webpackConfigEnv, argv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "eronkan",
    projectName: "sguide",
    webpackConfigEnv,
    argv,
  });

  return merge(defaultConfig, {
    // modify the webpack config however you'd like to by adding to this object
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: [
            require.resolve('style-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            require.resolve('css-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            'postcss-loader',
          ],
        },
      ],
    },
  });
};

`

**Comment by mdtalha-eronkan** [comment]
`facing this issue:

./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./src/global.css 39 bytes [built] [code generated] [1 error]

ERROR in ./src/global.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./src/global.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(2:7) /home/eronkan/Desktop/Project/sguide/src/global.css Unknown word

  1 | 
> 2 |       import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
 @ ./src/global.css 8:6-251 22:17-24 26:7-21 52:25-39 53:36-47 53:50-64 57:6-67:7 58:54-65 58:68-82 64:42-53 64:56-70 66:21-28 77:0-221 77:0-221 78:22-29 78:33-47 78:50-64 55:4-68:5
 @ ./src/eronkan-sguide.js 1:0-22

webpack 5.88.2 compiled with 1 error in 1851 ms


global.css file:

@tailwind base;
@tailwind components;
@tailwind utilities;


webpack config:


const {merge} = require('webpack-merge')
const singleSpaDefaults = require('webpack-config-single-spa-react')


module.exports = (webpackConfigEnv, argv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "eronkan",
    projectName: "sguide",
    webpackConfigEnv,
    argv,
  });

  return merge(defaultConfig, {
    // modify the webpack config however you'd like to by adding to this object
    module: {
      rules: [
        {
          test: /\.css$/i,
          use: [
            require.resolve('style-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            require.resolve('css-loader', {
              paths: [require.resolve('webpack-config-single-spa')],
            }),
            'postcss-loader',
          ],
        },
      ],
    },
  });
};

`

**Comment by thejayhaykid** [comment]
What are your `postcss.config.js` and your `tailwind.config.js`? Do they match what is on Tailwind's site linked above?

**Comment by mdtalha-eronkan** [comment]
yeah it as exactly same as it is mentioned in tailwind's site

**Comment by thejayhaykid** [comment]
Is this a public repo? Everything looks right so far

**Comment by mdtalha-eronkan** [comment]
yeah, link of my styleGuide repo: https://github.com/mdtalha-eronkan/react-mf-styleguide

**Comment by thejayhaykid** [comment]
@mdtalha-eronkan I [opened a PR](https://github.com/mdtalha-eronkan/react-mf-styleguide/pull/1) and that was working on my machine, let me know if that doesn't work for you. You were really close, it's a very small change in the PR
